---
- name: Parse interfaces summary
  ansible.utils.cli_parse:
    command: "show interfaces"
    parser:
      name: ansible.netcommon.content_templates
    set_fact: interfaces_health


- name: Show Summary facts
  ansible.builtin.debug:
    msg: "{{ interfaces_health }}"
