---
- name: Invoke detect function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    operation: "detect"
    resources:
      - "interfaces"
      - "l2_interfaces"
      - "l3_interfaces"
