---
- name: Invoke gather function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    operation: "gather"
    resources:
      - "interfaces"
      - "l2_interfaces"
      - "l3_interfaces"
